defaults:
  - model: baseline
  - dataset: local_train
  - _self_

spec_param:
  sr: 16000
  n_mels: 128
trainer:
  load_checkpoint: False # if true model train else load from checkpoint
  path_check: "saved"
  resume_from: "saved" # path to checkpoint model
  epochs: 3000

  # dataset_param.train_data_path=/kaggle/input/datasets/a24998667/librispeech/train-clean-100/LibriSpeech/train-clean-100
  # dataset_param.val_data_path=/kaggle/input/datasets/a24998667/librispeech/test-clean/LibriSpeech/test-clean