batch_size: 16
train_data_path: "/kaggle/input/datasets/a24998667/librispeech/train-clean-100/LibriSpeech/train-clean-100"
val_data_path: "/kaggle/input/datasets/a24998667/librispeech/test-clean/LibriSpeech/test-clean"