batch_size: 16
train_data_path: "/home/vladik095/Рабочий стол/pytorch_project_template/data/datasets/librispeech/dev-clean"
val_data_path: "/home/vladik095/Рабочий стол/pytorch_project_template/data/datasets/librispeech/dev-clean"